# Generated by Django 5.0.3 on 2024-04-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customermodel_token'),
        ('products', '0004_productreviewmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReviewModel',
            new_name='ReviewModel',
        ),
    ]
